<a href="https://colab.research.google.com/github/szabeebzaliz7-a11y/Datascience-And-Gen-AI/blob/main/Numpy_and_Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. Create a numpy array containing the numbers from 1 to 10, and then reshape it to a 2x5
matrix.

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
array1=np.array([1,2,3,4,5,6,7,8,9,10])
print('array : ',array1)
array2=np.reshape(array1,(2,5))
print('reshaped array : ',array2)


array :  [ 1  2  3  4  5  6  7  8  9 10]
reshaped array :  [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


2.Create a numpy array containing the numbers from 1 to 20, and then extract the
elements between the 5th and 15th index.

In [ ]:
array=np.arange(1,21)
print('array : ',array)
extracted_array=array[5:16]
print('extracted array : ',extracted_array)


array :  [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
extracted array :  [ 6  7  8  9 10 11 12 13 14 15 16]


3.How to compute the mean, median, and standard deviation of a numpy array?Use the
array you created above

In [ ]:
array_mean=np.mean(extracted_array)
print('mean : ',array_mean)
array_median=np.median(extracted_array)
print('median : ',array_median)
array_std=np.std(extracted_array)
print('standard deviation : ',array_std)

mean :  11.0
median :  11.0
standard deviation :  3.1622776601683795


4. Write a NumPy program that creates a 2D array x of shape (3, 4) and a 1D array y of
shape (4,). Subtract y from each row of x using broadcasting.

In [ ]:
x=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
y=np.array([1,2,3,4])
print('x : ',x)
print('y : ',y)
result=x-y
print('result : ',result)

x :  [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
y :  [1 2 3 4]
result :  [[0 0 0 0]
 [4 4 4 4]
 [8 8 8 8]]


5. Create a dataframe with the following columns: name, age, and gender. The dataframe
should have 10 rows of data.
1) Add a new column to the data frame created in question 1, called occupation.
The values for this column should be Programmer, Manager, and Analyst,
corresponding to the rows in the dataframe.
2) Select the rows of the dataframe where the age is greater than or equal to 30.

3) Convert this dataframe to a CSV file and read that CSV file, and finally display
the contents.

In [ ]:
data={
    'name':["Alice", "Bob", "Charlie", "Diana", "Eve",
    "Frank", "Grace", "Heidi", "Ivan", "Judy"],
    'age':[20,22,21,23,25,26,30,30,22,31],
    'gender':['F','M','M','F','F','M','M','F','M','F']
}
dataframe=pd.DataFrame(data)
print(dataframe)


      name  age gender
0    Alice   20      F
1      Bob   22      M
2  Charlie   21      M
3    Diana   23      F
4      Eve   25      F
5    Frank   26      M
6    Grace   30      M
7    Heidi   30      F
8     Ivan   22      M
9     Judy   31      F


In [ ]:
dataframe['occupation']=['Programmer', 'Manager', 'Analyst','HR','Manager','Programmer','Analyst','HR','Programmer','Analyst']
print(dataframe)

      name  age gender  occupation
0    Alice   20      F  Programmer
1      Bob   22      M     Manager
2  Charlie   21      M     Analyst
3    Diana   23      F          HR
4      Eve   25      F     Manager
5    Frank   26      M  Programmer
6    Grace   30      M     Analyst
7    Heidi   30      F          HR
8     Ivan   22      M  Programmer
9     Judy   31      F     Analyst


In [ ]:
age=dataframe[dataframe['age']>=30]
print(age)

    name  age gender occupation
6  Grace   30      M    Analyst
7  Heidi   30      F         HR
9   Judy   31      F    Analyst


In [ ]:
dataframe.to_csv('dataframe.csv',index=False)
df=pd.read_csv('dataframe.csv')
print(df)

      name  age gender  occupation
0    Alice   20      F  Programmer
1      Bob   22      M     Manager
2  Charlie   21      M     Analyst
3    Diana   23      F          HR
4      Eve   25      F     Manager
5    Frank   26      M  Programmer
6    Grace   30      M     Analyst
7    Heidi   30      F          HR
8     Ivan   22      M  Programmer
9     Judy   31      F     Analyst
